# model
model_name_or_path: google/gemma-2b

# method
stage: pt
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# dataset
dataset: sotu_maskedAll
cutoff_len: 1024
preprocessing_num_workers: 16
template: gemma
new_special_tokens: "<DEBATE_START>,<DEBATE_END>,<ENT>"

# output
output_dir: saves/gemma-2b_sotu/
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 0.00005
num_train_epochs: 15.0
lr_scheduler_type: linear
warmup_steps: 500
fp16: true
optim: adamw_torch
max_grad_norm: 1.0
flash_attn: auto 
packing: False
lora_rank: 8 
lora_alpha: 16 
lora_dropout: 0 

